# Generated by Django 2.1.dev20171019014353 on 2017-10-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oryginal_link_text', models.CharField(max_length=200)),
                ('nice_link_text', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
