# Generated by Django 2.1.dev20171019014353 on 2017-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicelink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='nice_link_text',
            field=models.CharField(max_length=200),
        ),
    ]
