# Generated by Django 2.1.dev20171019014353 on 2017-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicelink', '0002_auto_20171020_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='nice_link_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
