# Generated by Django 2.1.dev20171019014353 on 2017-10-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicelink', '0005_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='links',
        ),
    ]
